version: "3.8"

services:
  excalidraw:
    build:
      context: .
    args:
        NODE_ENV: development
        VITE_APP_BACKEND_V2_GET_URL: https://excalidraw-storage.foxboy.cloud/api/v2/
        VITE_APP_BACKEND_V2_POST_URL: https://excalidraw-storage.foxboy.cloud/api/v2/post/
        VITE_APP_LIBRARY_URL: https://excalidraw-libraries.foxboy.cloud
        VITE_APP_LIBRARY_BACKEND: https://excalidraw-libraries.foxboy.cloud/libraries
        VITE_APP_PLUS_LP: https://draw.foxboy.cloudm
        VITE_APP_PLUS_APP: https://draw.foxboy.cloud
        VITE_APP_AI_BACKEND: https://oss-ai.excalidraw.com
        VITE_APP_WS_SERVER_URL: https://excalidraw-room.foxboy.cloud
        VITE_APP_FIREBASE_CONFIG: '{}'
        VITE_APP_ENABLE_TRACKING: false
    container_name: excalidraw
    ports:
      - "3000:80"
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules

volumes:
  notused:
